select *from Categories;
select *from CustomerCustomerDemo;
select *from CustomerDemographics;
select *from Customers;
select *from Employees;
select *from EmployeeTerritories;
select *from [Order Details];
select *from Orders;
select *from Products;
select *from Region;
select *from Shippers;
select *from Suppliers;
select *from Territories;
